spring:
  cache:
    type: simple
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        SQL: debug
        dialect:
          storage_engine: innodb
        format_sql: true
        show_sql: true
        use_sql_comments: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: 6000ms

oauth:
  kakao:
    client-id: ${OAUTH_KAKAO_CLIENT_ID}
    client-secret: ${OAUTH_KAKAO_CLIENT_SECRET}
    redirect-uri: ${OAUTH_KAKAO_REDIRECT_URI}
    uri:
      token-url: https://kauth.kakao.com/oauth/token
      user-info-url: https://kapi.kakao.com/v2/user/me

jwt:
  secret_key: ${JWT_SECRET_KEY}
  access_token:
    valid_time: ${JWT_ACCESS_TOKEN_VALID_TIME}
  refresh_token:
    valid_time: ${JWT_REFRESH_TOKEN_VALID_TIME}

cloud:
  aws:
    credentials:
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET_NAME}

ai:
  api:
    key: ${AI_API_KEY}